# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - quizutncn

on:
  push:
    branches:
      - main
  workflow_dispatch:

jjobs:
  build-and-deploy:
    runs-on: windows-latest  # Usa Windows para todo el proceso
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'
          
      - name: Install dependencies
        run: npm install
        
      - name: Create web.config
        run: |
          echo "<configuration><system.webServer><handlers><add name='iisnode' path='app.js' verb='*' modules='iisnode'/></handlers><rewrite><rules><rule name='DynamicContent'><match url='/*' /><action type='Rewrite' url='app.js'/></rule></rules></rewrite><iisnode watchedFiles='*.js;node_modules\*;routes\*.js;views\*.jade'/></system.webServer></configuration>" > web.config
          
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'quizutncn'
          slot-name: 'Production'
          package: .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_09C7667D381641DE8E2D91AF063B5977 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_F3C0643773E6431F93F0A4DC55ACE170 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_0BE0EB242CF242B29BD7D9510A46343E }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'quizutncn'
          slot-name: 'Production'
          package: .
          